### ISSUE TITLE
建议打包成 Ruby Gem 或 Node Package

### ISSUE THREAD

**Issue by winnie2012** [marvin1023/sassCore#1]
1. 建议打包成库，比如 Ruby Gem 或 Node Package，这样方便升级，一条命令直接升级最新版本。
2. 建议再出一个Saas版本，虽说 SCSS 很方便转换到 Sass ，但是每次升级还是麻烦，特别是使用包管理之后。

**Comment by F-happy** [comment]
ruby 的不清楚， 但是 npm package 的还是比较简单的，可以参考我自己的这个 [scss](https://github.com/F-happy/nuts-scss) 工具，就可以直接在 node 环境下使用。
